---
date: "2025-10-24"
title: How to Spot “Questionable Research Practices”-- and Never be Fooled by Bad Science Again - conference presentation held by Tamás Nagy
---
On the 24th of October 2025, Tamás Nagy the principal investigator of the Stress and Emotions Lab held a presentation at the Science Writers 2025 conference with his colleague, Jane Hergert. The presentation was entitled 'How to Spot “Questionable Research Practices”-- and Never be Fooled by Bad Science Again'. 

<!--more-->

In the conference session, Tamás Nagy and his colleague presented their work called the Bestiary of Questionable Research Practices in Psychology. The presentation abstract was as follows:

'Do you want to break a story like Stephanie Lee’s Brian Wansink piece or better cover the replication crisis? Or maybe you just want to feel more confident that you can spot shoddy science in the wild? This session will teach science journalists about “questionable research practices (QRPs),” a collection of bad behaviors that can lead to misleading science.  Shockingly, studies find that up to 50% of researchers across scientific disciplines engage in QRPs.  

Dr. Tamás Nagy and Dr. Jane Hergert have put together a “Bestiary of Questionable Research Practices” and, along with science journalist Rose Rimler, they will walk us through the ghouls, goblins, and critters that can turn scientific research from a fairy tale to a nightmare. We’ll go beyond p-hacking. We’ll also learn about HARKing, twisted manipulations, selective sampling, publishing bias, and more.  '

Congratulations for the presentation!