---
date: "2026-01-16"
title: A New R package for data blinding
---
A new R package was developed by Tamas Nagy and his colleagues, Marton Kovacs and Sarafoglou Alexandra. The package is called Vazul and is available for use. 

<!--more-->

Analysis blinding is a methodological approach designed to protect the confirmatory status of an analysis by concealing crucial test-relevant aspects of the data from the analysts. This article introduces the vazul package for R, which provides a comprehensive suite of tools for implementing masking and scrambling techniques. We discuss the theoretical foundations of analysis blinding, particularly as a complement or alternative to preregistration. 
 
The package allows researchers to maintain analytic flexibility while safeguarding against bias. By using vazul, data managers can easily generate blinded datasets that preserve essential distributional properties while obscuring associations or labels that could lead to biased decisions. We provide detailed examples of vector-level, data-frame-level, and row-wise blinding operations, and demonstrate how the package handles complex data structures such as hierarchical or repeated-measures designs.

The package is available at github: https://nthun.github.io/vazul/
